---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          # formatting
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-toml
          - id: check-json
          # versionning issues
          - id: check-merge-conflict
          - id: no-commit-to-branch
            args: [--branch, main]
          # structure
          - id: check-symlinks
          - id: destroyed-symlinks
          # Security
          - id: detect-private-key

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3.9

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.6.0
      hooks:
          - id: reorder-python-imports

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.27.1  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2  # or other specific tag
      hooks:
          - id: yamlfmt
